### ISSUE TITLE
Taking part in hacktoberfest

### ISSUE THREAD

**Issue by guyluz11** [Levi-Lesches/opencv_ffi#13]
It would be nice and increase in popularity if this repo would take part in [hacktoberfest](https://hacktoberfest.com/).

Repo should add `hacktoberfest` topics

![image](https://github.com/osociety/network_tools/assets/9304740/4aa9173d-fd17-417e-b25d-41412fc0a344)

and incoming PR add the following label `hacktoberfest-accepted`

![image](https://github.com/osociety/network_tools/assets/9304740/f14074e0-a1ad-497e-9ffc-754572327ab6)

**Comment by Levi-Lesches** [comment]
I appreciate the thought, but for now, this package will remain internal. I am open to PRs and tests but I will not be judging them any differently if they are marked `hacktoberfest` or not, I will judge them on the merit of their code.

**Comment by guyluz11** [comment]
hacktoberfest label just bring people because they are searching repo that includes it.

You should always accept only a good code.

**Comment by Levi-Lesches** [comment]
As someone who believes strongly in the power of open-source software, I do not agree that packages should have to plug another project or hackathon in order to be contributed to. I do not know much about Hacktoberfest, but they should really encourage their participants to look for repos in need of contribution rather than ones marked with a specific label.
