### ISSUE TITLE
Error Failed to load dynamic library 'libopencv_ffi.so'

### ISSUE THREAD

**Issue by guyluz11** [Levi-Lesches/opencv_ffi#9]
OS: Linux

```dart
/home/guyluz/Programs/flutter/bin/cache/dart-sdk/bin/dart --enable-asserts /home/guyluz/Documents/git/opencv_ffi/example/example.dart
Unhandled exception:
Invalid argument(s): Failed to load dynamic library 'libopencv_ffi.so': libopencv_ffi.so: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      nativeLib (package:opencv_ffi/src/ffi.dart:21:49)
#3      nativeLib (package:opencv_ffi/src/ffi.dart)
#4      new Camera.fromName (package:opencv_ffi/src/camera.dart:28:31)
#5      main (file:///home/guyluz/Documents/git/opencv_ffi/example/example.dart:6:57)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:19)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

Process finished with exit code 255

```

**Comment by Levi-Lesches** [comment]
As mentioned in #4, please add the full path of `dist` to your computer's `LD_LIBRARY_PATH` for Dart to find it.

**Comment by guyluz11** [comment]
It should be part of the readme.

Thanks it worked

**Comment by Levi-Lesches** [comment]
It is: 

> Add the dist folder to your PATH. Restart your terminal/IDE and run your project as normal.

> The script will output a command to add the dist folder to your LD_LIBRARY_PATH. You only need to run this command once, even if you modify and rebuild OpenCV, but you must run it again if you move the dist folder.

**Comment by SkytAsul** [comment]
I am getting this error after downloading the package using `flutter pub add opencv_ffi`. Is it expected behavior? Is it needed that I build the package myself?
EDIT: oops, didn't read the README enough.
I still have one question though: if I want to deploy my application, will it work normally or should the users also build OpenCV themselves?

**Comment by Levi-Lesches** [comment]
Currently, the plugin is lacking the ability to package itself, because Dart doesn't offer it. 

In the future, the [Native Assets](https://github.com/dart-lang/sdk/issues/50565) feature will cover this automatically for both Dart and Flutter. Currently, this _is_ possible to set this up in a somewhat hacky way for Flutter. [`opencv_camera`](https://github.com/Levi-Lesches/opencv_camera) is my attempt at that, but I don't believe it is fully ready. If you're familiar with CMake, you're welcome to see if you can get it working (you'll have to run `git submodule update --init` after cloning), but I am personally waiting for native assets to be ready first. 

You're also free to try [`opencv_dart`](https://pub.dev/packages/opencv_dart), a rewrite of this plugin which seems to have much more active maintenance and a specific focus on Flutter

**Comment by SkytAsul** [comment]
Thank you for the detailed answer!
I think I am too much of a newcomer in the Dart/Flutter ecosystem to try that by myself. I barely understand how FFI works.
The Native Assets feature seems to have advanced quite well though, I hope it will eventually meet your needs for the opencv package :)
